name: WordleHs
version: 0.1.0.0
github: "FabianVegaA/WordleHs"
license: BSD3
author: "Fabián"
maintainer: "example@example.com"
copyright: "2022 Fabián"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/FabianVegaA/WordleHs#readme>

dependencies:
  - base >= 4.7 && < 5
  - text >= 1.2.1.1
  - random >= 1.2.1.1
  - splitmix >= 0.1.0.4

library:
  source-dirs: src

executables:
  WordleHs-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - WordleHs

tests:
  WordleHs-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - WordleHs
